### ISSUE TITLE
User Story 4.4 - Front end implementation

### ISSUE THREAD

**Issue by emilymd** [cs361fall2018/project-team-9#118]
Here are some basic guidelines for front end stuff: 
There should be an image that shows what the submarine looks like, as well as a button showing the option to place one. There should also be an activation code that shows up once a user sinks an enemy ship, and an area to enter this code so that the weapon is upgraded to a space laser. There should be some sort of button configuration that send signals regarding what direction (N,S,E,W) the ships move in, and it should present an error message if the user tries to use it more than twice, or if the user hasn't sunk two or more enemy ships.

**Comment by Amanda-Crawford** [comment]
For the space laser stuff, maybe use the form and input html elements to create the place to put in the code? And maybe start with then remove a "hidden" class for the element?  Also, I put in a placeholder for an element with ID "sonarCodeEntry" so could you put that onto it?

Here's what I found for HTML forms: https://www.w3schools.com/html/html_forms.asp
